name = "p3_symmetric"
version = "0.1.0"
defaultTargets = ["p3_symmetric"]

[[lean_lib]]
name = "p3_symmetric"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
