-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_keccak]: function definitions
import Aeneas
import CoreModels
import P3Keccak.Extraction.Types
import P3Keccak.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace p3_keccak

/-- [p3_keccak::fallback::VECTOR_LEN]
    Source: 'keccak/src/fallback.rs', lines 10:0-10:32
    Visibility: public -/
@[global_simps, irreducible] def fallback.VECTOR_LEN : Std.Usize := 1#usize

/-- [p3_keccak::{impl core::clone::Clone for p3_keccak::KeccakF}::clone]:
    Source: 'keccak/src/lib.rs', lines 81:15-81:20
    Visibility: public -/
def KeccakF.Insts.CoreCloneClone.clone (self : KeccakF) : Result KeccakF := do
  ok self

/-- Trait implementation: [p3_keccak::{impl core::clone::Clone for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 81:15-81:20 -/
@[reducible]
def KeccakF.Insts.CoreCloneClone : core.clone.Clone KeccakF := {
  clone := KeccakF.Insts.CoreCloneClone.clone
}

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u64; 25usize]> for p3_keccak::KeccakF}::permute_mut]:
    Source: 'keccak/src/lib.rs', lines 85:4-87:5
    Visibility: public -/
def KeccakF.Insts.P3_symmetricPermutationPermutationArrayU6425.permute_mut
  (self : KeccakF) (input : Array Std.U64 25#usize) :
  Result (Array Std.U64 25#usize)
  := do
  tiny_keccak.keccakf.keccakf input

/-- [p3_keccak::fallback::{impl p3_symmetric::permutation::Permutation<[[u64; 1usize]; 25usize]> for p3_keccak::KeccakF}::permute_mut]:
    Source: 'keccak/src/fallback.rs', lines 13:4-16:5
    Visibility: public -/
def
  KeccakF.Insts.P3_symmetricPermutationPermutationArrayArrayU64125.permute_mut
  (self : KeccakF) (input : Array (Array Std.U64 1#usize) 25#usize) :
  Result (Array (Array Std.U64 1#usize) 25#usize)
  := do
  let (input1, input2, _) ←
    core.intrinsics.transmute (Array Std.U64 25#usize) input
  let _ ←
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayU6425.permute_mut self
      input1
  ok input2

/-- Trait implementation: [p3_keccak::fallback::{impl p3_symmetric::permutation::Permutation<[[u64; 1usize]; 25usize]> for p3_keccak::KeccakF}]
    Source: 'keccak/src/fallback.rs', lines 12:0-17:1 -/
@[reducible]
impl_def KeccakF.Insts.P3_symmetricPermutationPermutationArrayArrayU64125 :
  p3_symmetric.permutation.Permutation KeccakF (Array (Array Std.U64 1#usize)
  25#usize) := {
  corecloneCloneInst := KeccakF.Insts.CoreCloneClone
  corecloneCloneInst1 := core.Array.Insts.CoreCloneClone 25#usize
    (core.Array.Insts.CoreCloneClone 1#usize core.U64.Insts.CoreCloneClone)
  permute := p3_symmetric.permutation.Permutation.permute.default
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayArrayU64125
  permute_mut :=
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayArrayU64125.permute_mut
}

/-- Trait implementation: [p3_keccak::fallback::{impl p3_symmetric::permutation::CryptographicPermutation<[[u64; 1usize]; 25usize]> for p3_keccak::KeccakF}]
    Source: 'keccak/src/fallback.rs', lines 19:0-19:69 -/
@[reducible]
def
  KeccakF.Insts.P3_symmetricPermutationCryptographicPermutationArrayArrayU64125
  : p3_symmetric.permutation.CryptographicPermutation KeccakF (Array (Array
  Std.U64 1#usize) 25#usize) := {
  PermutationInst :=
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayArrayU64125
  corecloneCloneInst := core.Array.Insts.CoreCloneClone 25#usize
    (core.Array.Insts.CoreCloneClone 1#usize core.U64.Insts.CoreCloneClone)
}

/-- Trait implementation: [p3_keccak::{impl core::marker::Copy for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 81:9-81:13 -/
@[reducible]
def KeccakF.Insts.CoreMarkerCopy : core.marker.Copy KeccakF := {
  cloneCloneInst := KeccakF.Insts.CoreCloneClone
}

/-- Trait implementation: [p3_keccak::{impl core::fmt::Debug for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 81:22-81:27 -/
@[reducible]
def KeccakF.Insts.CoreFmtDebug : core.fmt.Debug KeccakF := {
  fmt := KeccakF.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u64; 25usize]> for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 84:0-88:1 -/
@[reducible]
impl_def KeccakF.Insts.P3_symmetricPermutationPermutationArrayU6425 :
  p3_symmetric.permutation.Permutation KeccakF (Array Std.U64 25#usize) := {
  corecloneCloneInst := KeccakF.Insts.CoreCloneClone
  corecloneCloneInst1 := core.Array.Insts.CoreCloneClone 25#usize
    core.U64.Insts.CoreCloneClone
  permute := p3_symmetric.permutation.Permutation.permute.default
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayU6425
  permute_mut :=
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayU6425.permute_mut
}

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::CryptographicPermutation<[u64; 25usize]> for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 90:0-90:55 -/
@[reducible]
def KeccakF.Insts.P3_symmetricPermutationCryptographicPermutationArrayU6425 :
  p3_symmetric.permutation.CryptographicPermutation KeccakF (Array Std.U64
  25#usize) := {
  PermutationInst := KeccakF.Insts.P3_symmetricPermutationPermutationArrayU6425
  corecloneCloneInst := core.Array.Insts.CoreCloneClone 25#usize
    core.U64.Insts.CoreCloneClone
}

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnMut<(usize,), u8> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure#1<'_0>}::call_mut]:
    Source: 'keccak/src/lib.rs', lines 100:29-103:9 -/
def
  PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
  (c : PermutationKeccakFArrayU8200.permute.closure_1)
  (tupled_args : Std.Usize) :
  Result (Std.U8 × PermutationKeccakFArrayU8200.permute.closure_1)
  := do
  let i ← tupled_args / 8#usize
  let u64_limb ← Array.index_usize c i
  let a ← core.num.U64.to_le_bytes u64_limb
  let i1 ← tupled_args % 8#usize
  let i2 ← Array.index_usize a i1
  ok (i2, c)

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnOnce<(usize,), u8> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure#1<'_0>}::call_once]:
    Source: 'keccak/src/lib.rs', lines 100:29-103:9 -/
def
  PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU8.call_once
  (c : PermutationKeccakFArrayU8200.permute.closure_1) (i : Std.Usize) :
  Result Std.U8
  := do
  let (i1, _) ←
    PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
      c i
  ok i1

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnOnce<(usize,), u8> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure#1<'_0>}]
    Source: 'keccak/src/lib.rs', lines 100:29-103:9 -/
@[reducible]
def
  PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU8
  : core.ops.function.FnOnce PermutationKeccakFArrayU8200.permute.closure_1
  Std.Usize Std.U8 := {
  call_once :=
    PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU8.call_once
}

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnMut<(usize,), u8> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure#1<'_0>}]
    Source: 'keccak/src/lib.rs', lines 100:29-103:9 -/
@[reducible]
def
  PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU8
  : core.ops.function.FnMut PermutationKeccakFArrayU8200.permute.closure_1
  Std.Usize Std.U8 := {
  FnOnceInst :=
    PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU8
  call_mut :=
    PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
}

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnMut<(usize,), u64> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure<'_0>}::call_mut]:
    Source: 'keccak/src/lib.rs', lines 94:61-96:9 -/
def
  PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : PermutationKeccakFArrayU8200.permute.closure) (tupled_args : Std.Usize)
  :
  Result (Std.U64 × PermutationKeccakFArrayU8200.permute.closure)
  := do
  let i ← tupled_args * 8#usize
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) c { start := i }
  let s1 ←
    core.Slice.Insts.CoreOpsIndexIndex.index
      (core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8) s { «end» := 8#usize }
  let r ←
    core.Array.Insts.CoreConvertTryFromShared0SliceTryFromSliceError.try_from
      8#usize core.U8.Insts.CoreMarkerCopy s1
  let a ←
    core.result.Result.unwrap core.array.TryFromSliceError.Insts.CoreFmtDebug r
  let i1 ← core.num.U64.from_le_bytes a
  ok (i1, c)

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnOnce<(usize,), u64> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure<'_0>}::call_once]:
    Source: 'keccak/src/lib.rs', lines 94:61-96:9 -/
def
  PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : PermutationKeccakFArrayU8200.permute.closure) (i : Std.Usize) :
  Result Std.U64
  := do
  let (i1, _) ←
    PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
      c i
  ok i1

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnOnce<(usize,), u64> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure<'_0>}]
    Source: 'keccak/src/lib.rs', lines 94:61-96:9 -/
@[reducible]
def
  PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  : core.ops.function.FnOnce PermutationKeccakFArrayU8200.permute.closure
  Std.Usize Std.U64 := {
  call_once :=
    PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::{impl core::ops::function::FnMut<(usize,), u64> for p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure<'_0>}]
    Source: 'keccak/src/lib.rs', lines 94:61-96:9 -/
@[reducible]
def
  PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
  : core.ops.function.FnMut PermutationKeccakFArrayU8200.permute.closure
  Std.Usize Std.U64 := {
  FnOnceInst :=
    PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute]:
    Source: 'keccak/src/lib.rs', lines 93:4-104:5
    Visibility: public -/
def KeccakF.Insts.P3_symmetricPermutationPermutationArrayU8200.permute
  (self : KeccakF) (input_u8s : Array Std.U8 200#usize) :
  Result (Array Std.U8 200#usize)
  := do
  let state_u64s ←
    core.array.from_fn 25#usize
      PermutationKeccakFArrayU8200.permute.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
      input_u8s
  let state_u64s1 ← tiny_keccak.keccakf.keccakf state_u64s
  core.array.from_fn 200#usize
    PermutationKeccakFArrayU8200.permute.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU8
    state_u64s1

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 92:0-105:1 -/
@[reducible]
impl_def KeccakF.Insts.P3_symmetricPermutationPermutationArrayU8200 :
  p3_symmetric.permutation.Permutation KeccakF (Array Std.U8 200#usize) := {
  corecloneCloneInst := KeccakF.Insts.CoreCloneClone
  corecloneCloneInst1 := core.Array.Insts.CoreCloneClone 200#usize
    core.U8.Insts.CoreCloneClone
  permute := KeccakF.Insts.P3_symmetricPermutationPermutationArrayU8200.permute
  permute_mut := p3_symmetric.permutation.Permutation.permute_mut.default
    KeccakF.Insts.P3_symmetricPermutationPermutationArrayU8200
}

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::permutation::CryptographicPermutation<[u8; 200usize]> for p3_keccak::KeccakF}]
    Source: 'keccak/src/lib.rs', lines 107:0-107:55 -/
@[reducible]
def KeccakF.Insts.P3_symmetricPermutationCryptographicPermutationArrayU8200 :
  p3_symmetric.permutation.CryptographicPermutation KeccakF (Array Std.U8
  200#usize) := {
  PermutationInst := KeccakF.Insts.P3_symmetricPermutationPermutationArrayU8200
  corecloneCloneInst := core.Array.Insts.CoreCloneClone 200#usize
    core.U8.Insts.CoreCloneClone
}

/-- [p3_keccak::{impl core::clone::Clone for p3_keccak::Keccak256Hash}::clone]:
    Source: 'keccak/src/lib.rs', lines 111:15-111:20
    Visibility: public -/
def Keccak256Hash.Insts.CoreCloneClone.clone
  (self : Keccak256Hash) : Result Keccak256Hash := do
  ok self

/-- Trait implementation: [p3_keccak::{impl core::clone::Clone for p3_keccak::Keccak256Hash}]
    Source: 'keccak/src/lib.rs', lines 111:15-111:20 -/
@[reducible]
def Keccak256Hash.Insts.CoreCloneClone : core.clone.Clone Keccak256Hash := {
  clone := Keccak256Hash.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [p3_keccak::{impl core::marker::Copy for p3_keccak::Keccak256Hash}]
    Source: 'keccak/src/lib.rs', lines 111:9-111:13 -/
@[reducible]
def Keccak256Hash.Insts.CoreMarkerCopy : core.marker.Copy Keccak256Hash := {
  cloneCloneInst := Keccak256Hash.Insts.CoreCloneClone
}

/-- Trait implementation: [p3_keccak::{impl core::fmt::Debug for p3_keccak::Keccak256Hash}]
    Source: 'keccak/src/lib.rs', lines 111:22-111:27 -/
@[reducible]
def Keccak256Hash.Insts.CoreFmtDebug : core.fmt.Debug Keccak256Hash := {
  fmt := Keccak256Hash.Insts.CoreFmtDebug.fmt
}

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter_slices]: loop body 0:
    Source: 'keccak/src/lib.rs', lines 133:8-135:9
    Visibility: public -/
@[rust_loop_body]
def
  Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop.body
  {Clause0_IntoIter : Type}
  (iterIteratorInst :
  core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8))
  (iter : Clause0_IntoIter)
  (hasher : tiny_keccak.keccak.Keccak) :
  Result (ControlFlow (Clause0_IntoIter × tiny_keccak.keccak.Keccak)
    tiny_keccak.keccak.Keccak)
  := do
  let (o, iter1) ← iterIteratorInst.next iter
  match o with
  | core.option.Option.None => ok (done hasher)
  | core.option.Option.Some chunk =>
    let hasher1 ←
      tiny_keccak.keccak.Keccak.Insts.Tiny_keccakHasher.update hasher chunk
    ok (cont (iter1, hasher1))

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter_slices]: loop 0:
    Source: 'keccak/src/lib.rs', lines 133:8-135:9
    Visibility: public -/
@[rust_loop]
def
  Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop
  {Clause0_IntoIter : Type}
  (iterIteratorInst :
  core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8))
  (iter : Clause0_IntoIter)
  (hasher : tiny_keccak.keccak.Keccak) :
  Result tiny_keccak.keccak.Keccak
  := do
  loop
    (fun (iter1, hasher1) =>
      Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop.body
      iterIteratorInst iter1 hasher1)
    (iter, hasher)

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter_slices]:
    Source: 'keccak/src/lib.rs', lines 128:4-140:5
    Visibility: public -/
def
  Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorISharedASliceU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I (Slice Std.U8) Clause0_IntoIter)
  (iterIteratorInst :
  core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8))
  (self : Keccak256Hash) (input : I) :
  Result (Array Std.U8 32#usize)
  := do
  let hasher ← tiny_keccak.keccak.Keccak.v256
  let iter ←
    coreitertraitscollectIntoIteratorISharedASliceU8Clause0_IntoIterInst.into_iter
      input
  let hasher1 ←
    Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop
      iterIteratorInst iter hasher
  let output := Array.repeat 32#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut output)
  let s1 ←
    tiny_keccak.keccak.Keccak.Insts.Tiny_keccakHasher.finalize hasher1 s
  ok (to_slice_mut_back s1)

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::{impl core::ops::function::FnMut<(&'_ [u8],), ()> for p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::closure<'_0, I, Clause0_IntoIter>}::call_mut]:
    Source: 'keccak/src/lib.rs', lines 121:56-121:80 -/
def
  CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple.call_mut
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter)
  (c : CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure I
  Clause0_IntoIter) (tupled_args : Slice Std.U8) :
  Result (Unit × (CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure
    I Clause0_IntoIter))
  := do
  let k ←
    tiny_keccak.keccak.Keccak.Insts.Tiny_keccakHasher.update c tupled_args
  ok ((), k)

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::{impl core::ops::function::FnOnce<(&'_ [u8],), ()> for p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::closure<'_0, I, Clause0_IntoIter>}::call_once]:
    Source: 'keccak/src/lib.rs', lines 121:56-121:80 -/
def
  CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple.call_once
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter)
  (c : CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure I
  Clause0_IntoIter) (s : Slice Std.U8) :
  Result Unit
  := do
  let _ ←
    CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple.call_mut
      coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst c s
  ok ()

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::{impl core::ops::function::FnOnce<(&'_ [u8],), ()> for p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::closure<'_0, I, Clause0_IntoIter>}]
    Source: 'keccak/src/lib.rs', lines 121:56-121:80 -/
@[reducible]
def
  CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter) :
  core.ops.function.FnOnce
  (CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure I
  Clause0_IntoIter) (Slice Std.U8) Unit := {
  call_once :=
    CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple.call_once
    coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
}

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::{impl core::ops::function::FnMut<(&'_ [u8],), ()> for p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::closure<'_0, I, Clause0_IntoIter>}]
    Source: 'keccak/src/lib.rs', lines 121:56-121:80 -/
@[reducible]
def
  CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter) :
  core.ops.function.FnMut
  (CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure I
  Clause0_IntoIter) (Slice Std.U8) Unit := {
  FnOnceInst :=
    CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple
    coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
  call_mut :=
    CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple.call_mut
    coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
}

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter]:
    Source: 'keccak/src/lib.rs', lines 115:4-126:5
    Visibility: public -/
def
  Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter)
  (self : Keccak256Hash) (input : I) :
  Result (Array Std.U8 32#usize)
  := do
  let hasher ← tiny_keccak.keccak.Keccak.v256
  let c ←
    p3_util.apply_to_chunks 512#usize
      coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
      (CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple
      coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst) input hasher
  let output := Array.repeat 32#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut output)
  let s1 ← tiny_keccak.keccak.Keccak.Insts.Tiny_keccakHasher.finalize c s
  ok (to_slice_mut_back s1)

/-- Trait implementation: [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}]
    Source: 'keccak/src/lib.rs', lines 114:0-141:1 -/
@[reducible]
def Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832 :
  p3_symmetric.hasher.CryptographicHasher Keccak256Hash Std.U8 (Array Std.U8
  32#usize) := {
  corecloneCloneInst := Keccak256Hash.Insts.CoreCloneClone
  corecloneCloneInst1 := core.U8.Insts.CoreCloneClone
  hash_iter := fun {I : Type} {Clause0_IntoIter : Type}
    (coreitertraitscollectIntoIteratorPU8PInst :
    core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter) =>
    Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter
    coreitertraitscollectIntoIteratorPU8PInst
  hash_iter_slices := fun {I : Type} {Clause0_IntoIter : Type}
    (coreitertraitscollectIntoIteratorPSharedSliceU8PInst :
    core.iter.traits.collect.IntoIterator I (Slice Std.U8) Clause0_IntoIter)
    (iterIteratorInst :
    core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8)) =>
    Keccak256Hash.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices
    coreitertraitscollectIntoIteratorPSharedSliceU8PInst iterIteratorInst
}

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::BUFLEN]
    Source: 'keccak/src/lib.rs', lines 119:8-119:34 -/
@[global_simps, irreducible]
def CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.BUFLEN : Std.Usize :=
  512#usize

end p3_keccak
