-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_keccak]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CoreModels
import P3Keccak.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open p3_keccak

/-- [p3_keccak::{impl core::fmt::Debug for p3_keccak::KeccakF}::fmt]:
    Source: 'keccak/src/lib.rs', lines 81:22-81:27
    Visibility: public -/
axiom KeccakF.Insts.CoreFmtDebug.fmt
  :
  KeccakF → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [p3_keccak::{impl core::fmt::Debug for p3_keccak::Keccak256Hash}::fmt]:
    Source: 'keccak/src/lib.rs', lines 111:22-111:27
    Visibility: public -/
axiom Keccak256Hash.Insts.CoreFmtDebug.fmt
  :
  Keccak256Hash → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

