-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_keccak]: external functions.
-- (filled from the generated template; the Debug fmt externals stay axioms)
import Aeneas
import CoreModels
import P3Keccak.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open p3_keccak

/-- [p3_keccak::{impl core::fmt::Debug for p3_keccak::KeccakF}::fmt]:
    Source: 'keccak/src/lib.rs', lines 81:22-81:27
    Visibility: public -/
axiom KeccakF.Insts.CoreFmtDebug.fmt
  :
  KeccakF → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [p3_keccak::{impl core::fmt::Debug for p3_keccak::Keccak256Hash}::fmt]:
    Source: 'keccak/src/lib.rs', lines 111:22-111:27
    Visibility: public -/
axiom Keccak256Hash.Insts.CoreFmtDebug.fmt
  :
  Keccak256Hash → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)


-- External (crates.io) dependency `tiny_keccak`, declared by hand — the
-- generated template omitted these. TRUSTED (TCB): the tiny_keccak Keccak-f
-- permutation and sponge operations. Signatures reconstructed from the call
-- sites in Funs.lean.
axiom tiny_keccak.keccakf.keccakf :
  Array Std.U64 25#usize → Result (Array Std.U64 25#usize)

axiom tiny_keccak.keccak.Keccak.v256 : Result tiny_keccak.keccak.Keccak

axiom tiny_keccak.keccak.Keccak.Insts.Tiny_keccakHasher.update :
  tiny_keccak.keccak.Keccak → Slice Std.U8 → Result tiny_keccak.keccak.Keccak

axiom tiny_keccak.keccak.Keccak.Insts.Tiny_keccakHasher.finalize :
  tiny_keccak.keccak.Keccak → Slice Std.U8 → Result (Slice Std.U8)

-- Default bodies of p3_symmetric::Permutation's methods (each is defined in
-- terms of the other in Rust; for owned values they coincide). Referenced by
-- the generated impls; @[trait_default] lets `impl_def` resolve the
-- self-referential fields.
@[trait_default]
def p3_symmetric.permutation.Permutation.permute.default {Self T : Type}
  (PermutationInst : p3_symmetric.permutation.Permutation Self T)
  (self : Self) (input : T) : Result T :=
  PermutationInst.permute_mut self input

@[trait_default]
def p3_symmetric.permutation.Permutation.permute_mut.default {Self T : Type}
  (PermutationInst : p3_symmetric.permutation.Permutation Self T)
  (self : Self) (input : T) : Result T :=
  PermutationInst.permute self input

-- Debug witness for core::array::TryFromSliceError (absent from CoreModels).
def CoreModels.core.array.TryFromSliceError.Insts.CoreFmtDebug :
  CoreModels.core.fmt.Debug Aeneas.Std.core.array.TryFromSliceError :=
  { fmt := fun _ _ => Aeneas.Std.Result.fail .panic }

-- core::result::Result::unwrap — missing from CoreModels (which has unwrap_or
-- and map_err but no unwrap). Signature mirrors CoreModels' unwrap_or, plus the
-- Debug witness the generated call sites pass.
def CoreModels.core.result.Result.unwrap
  {T : Type} {E : Type} (_fmtDebugInst : CoreModels.core.fmt.Debug E)
  (self : CoreModels.core.result.Result T E) :
  Aeneas.Std.Result T :=
  match self with
  | .Ok t => Aeneas.Std.Result.ok t
  | .Err _ => Aeneas.Std.Result.fail .panic

-- p3_util::apply_to_chunks — dependency-crate function the pipeline did not
-- extract. TRUSTED (TCB): feeds an iterator of bytes to the FnMut closure in
-- chunks of at most `n`, threading the closure state.
axiom p3_util.apply_to_chunks {S I C : Type} (n : Std.Usize)
  (intoIterInst : core.iter.traits.collect.IntoIterator I Std.U8 C)
  (fnMutInst : core.ops.function.FnMut S (Slice Std.U8) Unit)
  (input : I) (state : S) : Result S

-- core::intrinsics::transmute — no model in hax-lean/aeneas. Shape matches the
-- generated &mut-transmute call (forward value, original-typed result,
-- backward function). TRUSTED (TCB); note the generated
-- fallback::permute_mut that uses it discards the permuted state (generator
-- defect, recorded in TCB.md) — do not use that impl for proofs.
axiom core.intrinsics.transmute {U : Type} (T : Type) (x : U) :
  Result (T × U × (T → U))
