-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_keccak]: external types.
-- (filled from the generated template)
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048


-- External (crates.io) dependency `tiny_keccak`: hax/aeneas does not translate
-- it, and the generated template declared no external types, so the opaque
-- carrier is declared here by hand. TRUSTED (TCB): the Keccak sponge state.
axiom tiny_keccak.keccak.Keccak : Type

-- Dependency-crate traits (p3_symmetric): the extraction references them but the
-- hax/aeneas pipeline emitted no declarations for dep-crate trait DECLS. Hand-
-- modeled here in aeneas's trait-as-structure encoding, shapes derived from the
-- generated impls in Funs.lean. The two Clone parent clauses get numbered field
-- names (the generator emitted a duplicate `corecloneCloneInst`; Funs.lean is
-- patched to match).
structure p3_symmetric.permutation.Permutation (Self T : Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecloneCloneInst1 : core.clone.Clone T
  permute : Self → T → Result T
  permute_mut : Self → T → Result T

structure p3_symmetric.permutation.CryptographicPermutation (Self T : Type) where
  PermutationInst : p3_symmetric.permutation.Permutation Self T
  corecloneCloneInst : core.clone.Clone T

structure p3_symmetric.hasher.CryptographicHasher (Self Item Out : Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecloneCloneInst1 : core.clone.Clone Item
  hash_iter : ∀ {I C : Type},
    core.iter.traits.collect.IntoIterator I Item C → Self → I → Result Out
  -- extended vs the Rust trait: hax-lean's IntoIterator carries no Iterator
  -- clause for its IntoIter type, so the iterator instance is passed explicitly
  -- (reconcile.py threads it through the generated hash_iter_slices).
  hash_iter_slices : ∀ {I C : Type},
    core.iter.traits.collect.IntoIterator I (Slice Item) C →
    core.iter.traits.iterator.Iterator C (Slice Item) → Self → I → Result Out
