-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_keccak]: type definitions
import Aeneas
import CoreModels
import P3Keccak.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace p3_keccak

/-- [p3_keccak::KeccakF]
    Source: 'keccak/src/lib.rs', lines 82:0-82:19
    Visibility: public -/
@[reducible]
def KeccakF := Unit

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure#1]
    Source: 'keccak/src/lib.rs', lines 100:29-103:9 -/
@[reducible]
def PermutationKeccakFArrayU8200.permute.closure_1 := Array Std.U64 25#usize

/-- [p3_keccak::{impl p3_symmetric::permutation::Permutation<[u8; 200usize]> for p3_keccak::KeccakF}::permute::closure]
    Source: 'keccak/src/lib.rs', lines 94:61-96:9 -/
@[reducible]
def PermutationKeccakFArrayU8200.permute.closure := Array Std.U8 200#usize

/-- [p3_keccak::Keccak256Hash]
    Source: 'keccak/src/lib.rs', lines 112:0-112:25
    Visibility: public -/
@[reducible]
def Keccak256Hash := Unit

/-- [p3_keccak::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_keccak::Keccak256Hash}::hash_iter::closure]
    Source: 'keccak/src/lib.rs', lines 121:56-121:80 -/
@[reducible]
def CryptographicHasherKeccak256HashU8ArrayU832.hash_iter.closure (I : Type)
  (Clause0_IntoIter : Type) :=
  tiny_keccak.keccak.Keccak

end p3_keccak
