-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_blake3]: external functions.
-- (filled from the generated template; externals stay axioms)
import Aeneas
import CoreModels
import P3Blake3.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open p3_blake3

/-- [p3_blake3::{impl core::fmt::Debug for p3_blake3::Blake3}::fmt]:
    Source: 'blake3/src/lib.rs', lines 8:22-8:27
    Visibility: public -/
axiom Blake3.Insts.CoreFmtDebug.fmt
  :
  Blake3 → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)


-- External (crates.io) dependency `blake3` — hand-declared. TRUSTED (TCB).
-- `update` keeps the generated backward-function pair shape.
axiom blake3.Hasher.new : Result blake3.Hasher
axiom blake3.Hasher.update :
  blake3.Hasher → Slice Std.U8 →
  Result (blake3.Hasher × (blake3.Hasher → blake3.Hasher))
axiom blake3.Hasher.finalize : blake3.Hasher → Result blake3.Hash
axiom blake3.ArrayU832.Insts.CoreConvertFromHash :
  core.convert.From (Array Std.U8 32#usize) blake3.Hash

-- p3_util::apply_to_chunks — dependency-crate function the pipeline did not
-- extract. TRUSTED (TCB); same declaration as in keccak's extraction.
axiom p3_util.apply_to_chunks {S I C : Type} (n : Std.Usize)
  (intoIterInst : core.iter.traits.collect.IntoIterator I Std.U8 C)
  (fnMutInst : core.ops.function.FnMut S (Slice Std.U8) Unit)
  (input : I) (state : S) : Result S
