-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_blake3]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CoreModels
import P3Blake3.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open p3_blake3

/-- [p3_blake3::{impl core::fmt::Debug for p3_blake3::Blake3}::fmt]:
    Source: 'blake3/src/lib.rs', lines 8:22-8:27
    Visibility: public -/
axiom Blake3.Insts.CoreFmtDebug.fmt
  :
  Blake3 → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

