-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_blake3]: function definitions
import Aeneas
import CoreModels
import P3Blake3.Extraction.Types
import P3Blake3.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace p3_blake3

/-- [p3_blake3::{impl core::clone::Clone for p3_blake3::Blake3}::clone]:
    Source: 'blake3/src/lib.rs', lines 8:15-8:20
    Visibility: public -/
def Blake3.Insts.CoreCloneClone.clone (self : Blake3) : Result Blake3 := do
  ok self

/-- Trait implementation: [p3_blake3::{impl core::clone::Clone for p3_blake3::Blake3}]
    Source: 'blake3/src/lib.rs', lines 8:15-8:20 -/
@[reducible]
def Blake3.Insts.CoreCloneClone : core.clone.Clone Blake3 := {
  clone := Blake3.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [p3_blake3::{impl core::marker::Copy for p3_blake3::Blake3}]
    Source: 'blake3/src/lib.rs', lines 8:9-8:13 -/
@[reducible]
def Blake3.Insts.CoreMarkerCopy : core.marker.Copy Blake3 := {
  cloneCloneInst := Blake3.Insts.CoreCloneClone
}

/-- Trait implementation: [p3_blake3::{impl core::fmt::Debug for p3_blake3::Blake3}]
    Source: 'blake3/src/lib.rs', lines 8:22-8:27 -/
@[reducible]
def Blake3.Insts.CoreFmtDebug : core.fmt.Debug Blake3 := {
  fmt := Blake3.Insts.CoreFmtDebug.fmt
}

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter_slices]: loop body 0:
    Source: 'blake3/src/lib.rs', lines 29:8-31:9
    Visibility: public -/
@[rust_loop_body]
def
  Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop.body
  {Clause0_IntoIter : Type}
  (iterIteratorInst :
  core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8))
  (iter : Clause0_IntoIter) (hasher : blake3.Hasher)
  :
  Result (ControlFlow (Clause0_IntoIter × blake3.Hasher) blake3.Hasher)
  := do
  let (o, iter1) ← iterIteratorInst.next iter
  match o with
  | core.option.Option.None => ok (done hasher)
  | core.option.Option.Some chunk =>
    let (h, update_back) ← blake3.Hasher.update hasher chunk
    let hasher1 := update_back h
    ok (cont (iter1, hasher1))

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter_slices]: loop 0:
    Source: 'blake3/src/lib.rs', lines 29:8-31:9
    Visibility: public -/
@[rust_loop]
def
  Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop
  {Clause0_IntoIter : Type}
  (iterIteratorInst :
  core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8))
  (iter : Clause0_IntoIter) (hasher : blake3.Hasher)
  :
  Result blake3.Hasher
  := do
  loop
    (fun (iter1, hasher1) =>
      Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop.body
      iterIteratorInst iter1 hasher1)
    (iter, hasher)

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter_slices]:
    Source: 'blake3/src/lib.rs', lines 24:4-33:5
    Visibility: public -/
def
  Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorISharedASliceU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I (Slice Std.U8) Clause0_IntoIter)
  (iterIteratorInst :
  core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8))
  (self : Blake3) (input : I) :
  Result (Array Std.U8 32#usize)
  := do
  let hasher ← blake3.Hasher.new
  let iter ←
    coreitertraitscollectIntoIteratorISharedASliceU8Clause0_IntoIterInst.into_iter
      input
  let hasher1 ←
    Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices_loop
      iterIteratorInst iter hasher
  let h ← blake3.Hasher.finalize hasher1
  core.convert.Into.Blanket.into blake3.ArrayU832.Insts.CoreConvertFromHash h

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::{impl core::ops::function::FnMut<(&'_ [u8],), ()> for p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::closure<'_0, I, Clause0_IntoIter>}::call_mut]:
    Source: 'blake3/src/lib.rs', lines 18:56-20:9 -/
def
  CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple.call_mut
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter)
  (c : CryptographicHasherBlake3U8ArrayU832.hash_iter.closure I
  Clause0_IntoIter) (tupled_args : Slice Std.U8) :
  Result (Unit × (CryptographicHasherBlake3U8ArrayU832.hash_iter.closure
    I Clause0_IntoIter))
  := do
  let (h, update_back) ← blake3.Hasher.update c tupled_args
  let h1 := update_back h
  ok ((), h1)

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::{impl core::ops::function::FnOnce<(&'_ [u8],), ()> for p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::closure<'_0, I, Clause0_IntoIter>}::call_once]:
    Source: 'blake3/src/lib.rs', lines 18:56-20:9 -/
def
  CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple.call_once
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter)
  (c : CryptographicHasherBlake3U8ArrayU832.hash_iter.closure I
  Clause0_IntoIter) (s : Slice Std.U8) :
  Result Unit
  := do
  let _ ←
    CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple.call_mut
      coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst c s
  ok ()

/-- Trait implementation: [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::{impl core::ops::function::FnOnce<(&'_ [u8],), ()> for p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::closure<'_0, I, Clause0_IntoIter>}]
    Source: 'blake3/src/lib.rs', lines 18:56-20:9 -/
@[reducible]
def
  CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter) :
  core.ops.function.FnOnce
  (CryptographicHasherBlake3U8ArrayU832.hash_iter.closure I Clause0_IntoIter)
  (Slice Std.U8) Unit := {
  call_once :=
    CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple.call_once
    coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
}

/-- Trait implementation: [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::{impl core::ops::function::FnMut<(&'_ [u8],), ()> for p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::closure<'_0, I, Clause0_IntoIter>}]
    Source: 'blake3/src/lib.rs', lines 18:56-20:9 -/
@[reducible]
def
  CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter) :
  core.ops.function.FnMut
  (CryptographicHasherBlake3U8ArrayU832.hash_iter.closure I Clause0_IntoIter)
  (Slice Std.U8) Unit := {
  FnOnceInst :=
    CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnOnceTupleSharedSliceU8Tuple
    coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
  call_mut :=
    CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple.call_mut
    coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
}

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter]:
    Source: 'blake3/src/lib.rs', lines 12:4-22:5
    Visibility: public -/
def Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter)
  (self : Blake3) (input : I) :
  Result (Array Std.U8 32#usize)
  := do
  let hasher ← blake3.Hasher.new
  let c ←
    p3_util.apply_to_chunks 512#usize
      coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst
      (CryptographicHasherBlake3U8ArrayU832.hash_iter.closure.Insts.CoreOpsFunctionFnMutTupleSharedSliceU8Tuple
      coreitertraitscollectIntoIteratorIU8Clause0_IntoIterInst) input hasher
  let h ← blake3.Hasher.finalize c
  core.convert.Into.Blanket.into blake3.ArrayU832.Insts.CoreConvertFromHash h

/-- Trait implementation: [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}]
    Source: 'blake3/src/lib.rs', lines 11:0-34:1 -/
@[reducible]
def Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832 :
  p3_symmetric.hasher.CryptographicHasher Blake3 Std.U8 (Array Std.U8 32#usize)
  := {
  corecloneCloneInst := Blake3.Insts.CoreCloneClone
  corecloneCloneInst1 := core.U8.Insts.CoreCloneClone
  hash_iter := fun {I : Type} {Clause0_IntoIter : Type}
    (coreitertraitscollectIntoIteratorPU8PInst :
    core.iter.traits.collect.IntoIterator I Std.U8 Clause0_IntoIter) =>
    Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter
    coreitertraitscollectIntoIteratorPU8PInst
  hash_iter_slices := fun {I : Type} {Clause0_IntoIter : Type}
    (coreitertraitscollectIntoIteratorPSharedSliceU8PInst :
    core.iter.traits.collect.IntoIterator I (Slice Std.U8) Clause0_IntoIter)
    (iterIteratorInst :
    core.iter.traits.iterator.Iterator Clause0_IntoIter (Slice Std.U8)) =>
    Blake3.Insts.P3_symmetricHasherCryptographicHasherU8ArrayU832.hash_iter_slices
    coreitertraitscollectIntoIteratorPSharedSliceU8PInst iterIteratorInst
}

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::BUFLEN]
    Source: 'blake3/src/lib.rs', lines 16:8-16:34 -/
@[global_simps, irreducible]
def CryptographicHasherBlake3U8ArrayU832.hash_iter.BUFLEN : Std.Usize :=
  512#usize

end p3_blake3
