-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_blake3]: external types.
-- (filled from the generated template)
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048


-- External (crates.io) dependency `blake3`: opaque carriers. TRUSTED (TCB).
axiom blake3.Hasher : Type
axiom blake3.Hash : Type

-- Dependency-crate trait (p3_symmetric): hand-modeled, same encoding and
-- naming as in keccak's extraction (see keccak/proofs/lean).
structure p3_symmetric.hasher.CryptographicHasher (Self Item Out : Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecloneCloneInst1 : core.clone.Clone Item
  hash_iter : ∀ {I C : Type},
    core.iter.traits.collect.IntoIterator I Item C → Self → I → Result Out
  hash_iter_slices : ∀ {I C : Type},
    core.iter.traits.collect.IntoIterator I (Slice Item) C →
    core.iter.traits.iterator.Iterator C (Slice Item) → Self → I → Result Out
