-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_blake3]: type definitions
import Aeneas
import CoreModels
import P3Blake3.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace p3_blake3

/-- [p3_blake3::Blake3]
    Source: 'blake3/src/lib.rs', lines 9:0-9:18
    Visibility: public -/
@[reducible]
def Blake3 := Unit

/-- [p3_blake3::{impl p3_symmetric::hasher::CryptographicHasher<u8, [u8; 32usize]> for p3_blake3::Blake3}::hash_iter::closure]
    Source: 'blake3/src/lib.rs', lines 18:56-20:9 -/
@[reducible]
def CryptographicHasherBlake3U8ArrayU832.hash_iter.closure (I : Type)
  (Clause0_IntoIter : Type) :=
  blake3.Hasher

end p3_blake3
